{"name": "test_b", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_demo3.Test_ABC object at 0x0000021547B8B808>\n\n    def test_b(self):\n        print('----test_b')\n>       assert False\nE       assert False\n\ntest_demo3.py:25: AssertionError"}, "attachments": [{"name": "stdout", "source": "cc3d717d-d47d-4756-adbc-fb5a8efaa0af-attachment.txt", "type": "text/plain"}], "start": 1598364968811, "stop": 1598364968811, "uuid": "2984187b-9270-4d5a-8b69-5b6e9b01c755", "historyId": "1c338a1f58623b5dafa8da98805a6c5e", "testCaseId": "f8b910b6fbdef4d5e998d627c50e5a44", "fullName": "test_demo3.Test_ABC#test_b", "labels": [{"name": "suite", "value": "test_demo3"}, {"name": "subSuite", "value": "Test_ABC"}, {"name": "host", "value": "DESKTOP-KHV2FO1"}, {"name": "thread", "value": "15500-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo3"}]}